[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "pricing-simulator"
version = "0.1.0"
description = "A pricing simulator game"
requires-python = ">=3.8"

[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
